name: Test OCI Setup Script

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test script
      run: |
        chmod +x oci-setup.sh
        sudo ./oci-setup.sh
